//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuTungXeMay2019.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CONTACT
    {
        [Display(Name="ID liên hệ")]
        public int idContact { get; set; }
        [Display(Name = "Tên liên hệ")]
        public string tenContact { get; set; }
          [Display(Name = "Nội dung liên hệ")]
        public string noidungContact { get; set; }
          [Display(Name="Id Người dùng")]
        public Nullable<int> idNguoidung { get; set; }
          [Display(Name="Tên Người dùng")]
        public string tenNguoidung { get; set; }
          [Display(Name="Tên liên hệ")]
        public byte[] hinhanhNguoidung { get; set; }
          [Display(Name="Giới tính")]
        public string gioitinh { get; set; }
          [Display(Name="Địa chỉ")]
        public string diachi { get; set; }
          [Display(Name="SĐT")]
        public Nullable<int> sdt { get; set; }
          [Display(Name="Ghi chú")]
        public string ghichu { get; set; }
    }
}
