//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuTungXeMay2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khachhang
    {
        public Khachhang()
        {
            this.Dathangs = new HashSet<Dathang>();
        }
    
        public int Idkhachhang { get; set; }
        public string Email { get; set; }
        public string Tendangnhap { get; set; }
        public string Matkhau { get; set; }
        public string Diachi { get; set; }
    
        public virtual ICollection<Dathang> Dathangs { get; set; }
    }
}
