//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuTungXeMay2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lienhe
    {
        public int id { get; set; }
        public string Tieude { get; set; }
        public string Tenlh { get; set; }
        public string Email { get; set; }
        public int Sdt { get; set; }
        public string Noidung { get; set; }
    }
}
