//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuTungXeMay2019.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Sanpham
    {
        [Display(Name="id sản phẩm")]
        public int id { get; set; }
        [Display(Name = "Tên sản phẩm")]
        public string Tensp { get; set; }
        [Display(Name = "Loại sản phẩm")]
        public string Loaisp { get; set; }
        [Display(Name = "Giá")]
        public int Gia { get; set; }
        [Display(Name = "Số lượng")]
        public int Soluong { get; set; }
        [Display(Name = "Xuất xứ")]
        public string Xuatxu { get; set; }
        [Display(Name = "Chi tiết")]
        public string Chitietsp { get; set; }
        [Display(Name = "Nhà sản xuất")]
        public string Nhasx { get; set; }
        [Display(Name = "Nhà cung cấp")]
        public string Nhacungcap { get; set; }
        [Display(Name = "Hình ảnh")]
        public byte[] Hinhanh { get; set; }
    }
}
