//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuTungXeMay2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableOrder
    {
        public int idSP { get; set; }
        public string tenSP { get; set; }
        public byte[] hinhSP { get; set; }
        public Nullable<int> dongiaSP { get; set; }
        public Nullable<int> soluongSP { get; set; }
        public Nullable<int> thanhtien { get; set; }
        public string ghichu { get; set; }
    }
}
